# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OneBuild.ui'
#
# Created: Mon Nov 17 09:53:29 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.Qt import *  
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindows(QtGui.QMainWindow):
    def setupUi(self, MainWindows):
        MainWindows.setObjectName(_fromUtf8("MainWindows"))
        MainWindows.setEnabled(True)
        MainWindows.resize(675, 400)
        MainWindows.setMaximumSize(QtCore.QSize(675, 382))
        MainWindows.setStyleSheet( open ( "./config/style.qss" , "r" ).read())


        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(9)
        MainWindows.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./icon/icon.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindows.setWindowIcon(icon)


        self.Tool_Path = QtGui.QTabWidget(MainWindows)
        self.Tool_Path.setGeometry(QtCore.QRect(70, 90, 291, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale WT J"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Tool_Path.setFont(font)
        self.Tool_Path.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Tool_Path.setStyleSheet(_fromUtf8("font: 8pt \"Andale WT J\";wang"))
        self.Tool_Path.setMovable(False)
        self.Tool_Path.setObjectName(_fromUtf8("Tool_Path"))
        self.Atl_tab = QtGui.QWidget()
        self.Atl_tab.setObjectName(_fromUtf8("Atl_tab"))
        self.Atl_Path_line = QtGui.QLineEdit(self.Atl_tab)
        self.Atl_Path_line.setGeometry(QtCore.QRect(0, 20, 270, 25))
        self.Atl_Path_line.setObjectName(_fromUtf8("Atl_Path_line"))
        
       
        
        self.Tool_Path.addTab(self.Atl_tab, _fromUtf8(""))
        self.Kds_tab = QtGui.QWidget()
        self.Kds_tab.setObjectName(_fromUtf8("Kds_tab"))
        self.Kds_Path_line = QtGui.QLineEdit(self.Kds_tab)
        self.Kds_Path_line.setGeometry(QtCore.QRect(0, 20, 270, 25))
        self.Kds_Path_line.setObjectName(_fromUtf8("Kds_Path_line"))
       
        self.Tool_Path.addTab(self.Kds_tab, _fromUtf8(""))
        self.Arm_tab = QtGui.QWidget()
        self.Arm_tab.setAccessibleName(_fromUtf8(""))
        self.Arm_tab.setObjectName(_fromUtf8("Arm_tab"))
        self.Arm_Path_line = QtGui.QLineEdit(self.Arm_tab)
        self.Arm_Path_line.setGeometry(QtCore.QRect(0, 20, 270, 25))
        self.Arm_Path_line.setText(_fromUtf8(""))
        self.Arm_Path_line.setObjectName(_fromUtf8("Arm_Path_line"))
       
        self.Tool_Path.addTab(self.Arm_tab, _fromUtf8(""))
        self.Iar_tab = QtGui.QWidget()
        self.Iar_tab.setObjectName(_fromUtf8("Iar_tab"))
        self.Iar_Path_line = QtGui.QLineEdit(self.Iar_tab)
        self.Iar_Path_line.setGeometry(QtCore.QRect(0, 20, 270, 25))
        self.Iar_Path_line.setText(_fromUtf8(""))
        self.Iar_Path_line.setObjectName(_fromUtf8("Iar_Path_line"))
       
        self.Tool_Path.addTab(self.Iar_tab, _fromUtf8(""))
        self.Uv4_tab = QtGui.QWidget()
        self.Uv4_tab.setObjectName(_fromUtf8("Uv4_tab"))
        self.Uv4_Path_line = QtGui.QLineEdit(self.Uv4_tab)
        self.Uv4_Path_line.setGeometry(QtCore.QRect(0, 20, 270, 25))
        self.Uv4_Path_line.setObjectName(_fromUtf8("Uv4_Path_line"))
       
        self.Tool_Path.addTab(self.Uv4_tab, _fromUtf8(""))
        self.App_list = QtGui.QListWidget(MainWindows)
        self.App_list.setGeometry(QtCore.QRect(550, 40, 121, 151))
        self.App_list.setObjectName(_fromUtf8("App_list"))
        
        self.Select_Kds = QtGui.QCheckBox(MainWindows)
        self.Select_Kds.setGeometry(QtCore.QRect(260, 290, 43, 19))
        self.Select_Kds.setObjectName(_fromUtf8("Select_Kds"))
        self.layoutWidget = QtGui.QWidget(MainWindows)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 290, 155, 62))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSpacing(60)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Select_Atl = QtGui.QCheckBox(self.layoutWidget)
        self.Select_Atl.setObjectName(_fromUtf8("Select_Atl"))
        self.verticalLayout.addWidget(self.Select_Atl)
        self.Select_Uv4 = QtGui.QCheckBox(self.layoutWidget)
        self.Select_Uv4.setObjectName(_fromUtf8("Select_Uv4"))
        self.verticalLayout.addWidget(self.Select_Uv4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.Select_Arm = QtGui.QCheckBox(self.layoutWidget)
        self.Select_Arm.setObjectName(_fromUtf8("Select_Arm"))
        self.verticalLayout_2.addWidget(self.Select_Arm)
        self.Select_Iar = QtGui.QCheckBox(self.layoutWidget)
        self.Select_Iar.setObjectName(_fromUtf8("Select_Iar"))
        self.verticalLayout_2.addWidget(self.Select_Iar)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.Main_Path_line = QtGui.QLineEdit(MainWindows)
        self.Main_Path_line.setGeometry(QtCore.QRect(70, 40, 281, 31))
        self.Main_Path_line.setText(_fromUtf8(""))
        self.Main_Path_line.setObjectName(_fromUtf8("Main_Path_line"))
        
        self.Select_IDE_label = QtGui.QLabel(MainWindows)
        self.Select_IDE_label.setGeometry(QtCore.QRect(10, 310, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Select_IDE_label.setFont(font)
        self.Select_IDE_label.setObjectName(_fromUtf8("Select_IDE_label"))
        self.save_progress = QtGui.QProgressBar(MainWindows)
        self.save_progress.setGeometry(QtCore.QRect(0, 360, 551, 23))
        self.save_progress.setProperty("value", 24)
        self.save_progress.setObjectName(_fromUtf8("save_progress"))
        self.Board_list = QtGui.QListWidget(MainWindows)
        self.Board_list.setGeometry(QtCore.QRect(550, 200, 121, 181))
        self.Board_list.setObjectName(_fromUtf8("BoardBox"))
        
        self.Select_board_label = QtGui.QLabel(MainWindows)
        self.Select_board_label.setGeometry(QtCore.QRect(400, 207, 71, 16))
        self.Select_board_label.setStyleSheet(_fromUtf8("font: 9pt \"Times New Roman\";"))
        self.Select_board_label.setObjectName(_fromUtf8("Select_board_label"))
        self.BoardBox = QtGui.QComboBox(MainWindows)
        self.BoardBox.setGeometry(QtCore.QRect(400, 235, 136, 21))

        self.stop = QtGui.QPushButton(MainWindows)
        self.stop.setGeometry(QtCore.QRect(400, 180, 141, 23))
        self.stop.setObjectName(_fromUtf8("Save"))

        self.clean_pre_build_info = QtGui.QPushButton(MainWindows)
        self.clean_pre_build_info.setGeometry(QtCore.QRect(400, 150, 141, 23))
        self.clean_pre_build_info.setObjectName(_fromUtf8("Save"))
        
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(9)
        self.BoardBox.setFont(font)
        self.BoardBox.setObjectName(_fromUtf8("BoardBox"))
        self.BoardBox.addItem(_fromUtf8(""))
        self.BoardBox.addItem(_fromUtf8(""))
        self.BoardBox.addItem(_fromUtf8(""))
        self.BoardBox.addItem(_fromUtf8(""))
        self.BoardBox.addItem(_fromUtf8(""))
        self.BoardBox.addItem(_fromUtf8(""))
        self.BoardBox.addItem(_fromUtf8(""))
        self.BoardBox.addItem(_fromUtf8(""))
        self.BoardBox.addItem(_fromUtf8(""))
        self.BoardBox.addItem(_fromUtf8(""))
        self.Build_board_all = QtGui.QCheckBox(MainWindows)
        self.Build_board_all.setGeometry(QtCore.QRect(480, 270, 70, 17))
        self.Build_board_all.setObjectName(_fromUtf8("Build_board_all"))
        self.Build_Lib = QtGui.QCheckBox(MainWindows)
        self.Build_Lib.setGeometry(QtCore.QRect(400, 270, 78, 19))
        self.Build_Lib.setObjectName(_fromUtf8("Build_Lib"))

        self.Save = QtGui.QPushButton(MainWindows)
        self.Save.setGeometry(QtCore.QRect(400, 305, 141, 23))
        self.Save.setObjectName(_fromUtf8("Save"))
        

        self.layoutWidget1 = QtGui.QWidget(MainWindows)
        self.layoutWidget1.setGeometry(QtCore.QRect(400, 40, 138, 59))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.Select_App_label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(9)
        font.setItalic(True)
        self.Select_App_label.setFont(font)
        self.Select_App_label.setObjectName(_fromUtf8("Select_App_label"))
        self.verticalLayout_3.addWidget(self.Select_App_label)
        self.CaseBox = QtGui.QComboBox(self.layoutWidget1)
        
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(9)
        self.CaseBox.setFont(font)
        self.CaseBox.setObjectName(_fromUtf8("CaseBox"))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.CaseBox.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.CaseBox)
        self.Build_App = QtGui.QCheckBox(MainWindows)
        self.Build_App.setGeometry(QtCore.QRect(400, 120, 65, 19))
        self.Build_App.setObjectName(_fromUtf8("Build_App"))
        self.label = QtGui.QLabel(MainWindows)
        self.label.setGeometry(QtCore.QRect(10, 220, 61, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.Select_freertos = QtGui.QCheckBox(MainWindows)
        self.Select_freertos.setGeometry(QtCore.QRect(70, 200, 70, 17))
        self.Select_freertos.setObjectName(_fromUtf8("Select_freertos"))
        self.Select_startup = QtGui.QCheckBox(MainWindows)
        self.Select_startup.setGeometry(QtCore.QRect(240, 200, 70, 17))
        self.Select_startup.setObjectName(_fromUtf8("Select_startup"))
        self.Select_std = QtGui.QCheckBox(MainWindows)
        self.Select_std.setGeometry(QtCore.QRect(240, 240, 70, 17))
        self.Select_std.setObjectName(_fromUtf8("Select_std"))
        self.Select_hal = QtGui.QCheckBox(MainWindows)
        self.Select_hal.setGeometry(QtCore.QRect(70, 240, 70, 17))
        self.Select_hal.setObjectName(_fromUtf8("Select_hal"))
        self.Select_mqx = QtGui.QCheckBox(MainWindows)
        self.Select_mqx.setGeometry(QtCore.QRect(150, 200, 70, 17))
        self.Select_mqx.setObjectName(_fromUtf8("Select_mqx"))
        self.Select_platform = QtGui.QCheckBox(MainWindows)
        self.Select_platform.setGeometry(QtCore.QRect(150, 240, 70, 17))
        self.Select_platform.setObjectName(_fromUtf8("Select_platform"))
        self.Select_ucosii = QtGui.QCheckBox(MainWindows)
        self.Select_ucosii.setGeometry(QtCore.QRect(310, 200, 70, 17))
        self.Select_ucosii.setObjectName(_fromUtf8("Select_ucosii"))
        self.Select_ucosiii = QtGui.QCheckBox(MainWindows)
        self.Select_ucosiii.setGeometry(QtCore.QRect(310, 240, 70, 17))
        self.Select_ucosiii.setObjectName(_fromUtf8("Select_ucosiii"))
        self.Run = QtGui.QPushButton(MainWindows)
        self.Run.setGeometry(QtCore.QRect(400, 345, 141, 23))
        self.Run.setObjectName(_fromUtf8("Run"))

        
        self.MainPath_label = QtGui.QLabel(MainWindows)
        self.MainPath_label.setGeometry(QtCore.QRect(10, 50, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MainPath_label.setFont(font)
        self.MainPath_label.setObjectName(_fromUtf8("MainPath_label"))
        self.ToolPath_label = QtGui.QLabel(MainWindows)
        self.ToolPath_label.setGeometry(QtCore.QRect(10, 150, 51, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ToolPath_label.setFont(font)
        self.ToolPath_label.setObjectName(_fromUtf8("ToolPath_label"))

        self.retranslateUi(MainWindows)
        self.Tool_Path.setCurrentIndex(0)
        

        
        QtCore.QMetaObject.connectSlotsByName(MainWindows)

    def retranslateUi(self, MainWindows):
        MainWindows.setWindowTitle(_translate("MainWindows", "One Builder", None))
        self.Tool_Path.setToolTip(_translate("MainWindows", "<html><head/><body><p>wang</p></body></html>", None))
        self.Tool_Path.setTabText(self.Tool_Path.indexOf(self.Atl_tab), _translate("MainWindows", "Atl", None))
        self.Tool_Path.setTabText(self.Tool_Path.indexOf(self.Kds_tab), _translate("MainWindows", "Kds", None))
        self.Tool_Path.setTabText(self.Tool_Path.indexOf(self.Arm_tab), _translate("MainWindows", "Arm", None))
        self.Tool_Path.setTabText(self.Tool_Path.indexOf(self.Iar_tab), _translate("MainWindows", "Iar", None))
        self.Tool_Path.setTabText(self.Tool_Path.indexOf(self.Uv4_tab), _translate("MainWindows", "Uv4", None))
        self.Select_Kds.setText(_translate("MainWindows", "Kds", None))
        self.Select_Atl.setText(_translate("MainWindows", "Atl", None))
        self.Select_Uv4.setText(_translate("MainWindows", "Uv4", None))
        self.Select_Arm.setText(_translate("MainWindows", "Arm", None))
        self.Select_Iar.setText(_translate("MainWindows", "Iar", None))
        self.Select_IDE_label.setText(_translate("MainWindows", "Select IDE", None))
        self.Select_board_label.setText(_translate("MainWindows", "<html><head/><body><p><span style=\" font-size:10pt;\">Select Board</span></p></body></html>", None))
        self.BoardBox.setItemText(0, _translate("MainWindows", "K02F12810", None))
        self.BoardBox.setItemText(1, _translate("MainWindows", "K22F51212", None))
        self.BoardBox.setItemText(2, _translate("MainWindows", "K24F25612", None))
        self.BoardBox.setItemText(3, _translate("MainWindows", "K60D10", None))
        self.BoardBox.setItemText(4, _translate("MainWindows", "K64F12", None))
        self.BoardBox.setItemText(5, _translate("MainWindows", "KL03Z4", None))
        self.BoardBox.setItemText(6, _translate("MainWindows", "KL46Z4", None))
        self.BoardBox.setItemText(7, _translate("MainWindows", "KV10Z7", None))
        self.BoardBox.setItemText(8, _translate("MainWindows", "KV30F12810", None))
        self.BoardBox.setItemText(9, _translate("MainWindows", "KV31F51212", None))
        self.Build_board_all.setText(_translate("MainWindows", "ALL", None))
        self.Build_Lib.setText(_translate("MainWindows", "Build Library", None))
        self.Save.setText(_translate("MainWindows", "Save", None))
        self.Select_App_label.setText(_translate("MainWindows", "<html><head/><body><p><span style=\" font-size:10pt; font-style:normal;\">Select App</span></p></body></html>", None))
        self.CaseBox.setItemText(0, _translate("MainWindows", "adc_hw_trigger", None))
        self.CaseBox.setItemText(1, _translate("MainWindows", "adc_low_power", None))
        self.CaseBox.setItemText(2, _translate("MainWindows", "bldc_demo", None))
        self.CaseBox.setItemText(3, _translate("MainWindows", "dac_adc_demo", None))
        self.CaseBox.setItemText(4, _translate("MainWindows", "flash_demo", None))
        self.CaseBox.setItemText(5, _translate("MainWindows", "flexcan_uart", None))
        self.CaseBox.setItemText(6, _translate("MainWindows", "freemaster_demo", None))
        self.CaseBox.setItemText(7, _translate("MainWindows", "ftm_pdb_adc_demo", None))
        self.CaseBox.setItemText(8, _translate("MainWindows", "hello_world", None))
        self.CaseBox.setItemText(9, _translate("MainWindows", "hwtimer_demo", None))
        self.CaseBox.setItemText(10, _translate("MainWindows", "i2c_comm", None))
        self.CaseBox.setItemText(11, _translate("MainWindows", "i2c_rtos", None))
        self.CaseBox.setItemText(12, _translate("MainWindows", "lptmr_demo", None))
        self.CaseBox.setItemText(13, _translate("MainWindows", "lwip_httpserver_demo", None))
        self.CaseBox.setItemText(14, _translate("MainWindows", "lwip_ping_demo", None))
        self.CaseBox.setItemText(15, _translate("MainWindows", "lwip_tcpecho_demo", None))
        self.CaseBox.setItemText(16, _translate("MainWindows", "lwip_udpecho_demo", None))
        self.CaseBox.setItemText(17, _translate("MainWindows", "mmdvsq_demo", None))
        self.CaseBox.setItemText(18, _translate("MainWindows", "power_manager_demo", None))
        self.CaseBox.setItemText(19, _translate("MainWindows", "rtc_func", None))
        self.CaseBox.setItemText(20, _translate("MainWindows", "sai_demo", None))
        self.CaseBox.setItemText(21, _translate("MainWindows", "sdhc_sdcard", None))
        self.CaseBox.setItemText(22, _translate("MainWindows", "thermistor_lab", None))
        self.CaseBox.setItemText(23, _translate("MainWindows", "wdog_reset", None))
        self.Build_App.setText(_translate("MainWindows", "Build App", None))
        self.label.setText(_translate("MainWindows", "<html><head/><body><p><span style=\" font-size:10pt;\">Select Lib</span></p></body></html>", None))
        self.Select_freertos.setText(_translate("MainWindows", "freertos", None))
        self.Select_startup.setText(_translate("MainWindows", "startup", None))
        self.Select_std.setText(_translate("MainWindows", "std", None))
        self.Select_hal.setText(_translate("MainWindows", "hal", None))
        self.Select_mqx.setText(_translate("MainWindows", "mqx", None))
        self.Select_platform.setText(_translate("MainWindows", "platform", None))
        self.Select_ucosii.setText(_translate("MainWindows", "ucosii", None))
        self.Select_ucosiii.setText(_translate("MainWindows", "ucosiii", None))
        self.Run.setText(_translate("MainWindows", "Run", None))
        self.stop.setText(_translate("MainWindows", "Stop", None))
        self.clean_pre_build_info.setText(_translate("MainWindows", "Clean build info", None))
        self.MainPath_label.setText(_translate("MainWindows", "Main Path", None))
        self.ToolPath_label.setText(_translate("MainWindows", "Tool Path", None))


