{arm: 'C:\PROGRA~1\GNUTOO~1\44F1D~1.820', atl: 'C:\Program Files\Atollic\TrueSTUDIO
    for ARM Pro 5.2.0', iar: 'C:\software\IAR\common\bin', kds: 'C:\Freescale\KDS_1.9.9',
  main_path: 'C:\code\KSDK_1.1.0-GA_RC3\KSDK_1.1.0', uv4: 'C:\software\Keil\UV4'}
